(add-hook 'c-mode-hook 'dumb-jump-mode)
(add-hook 'c++-mode-hook 'dumb-jump-mode)
(add-hook 'java-mode 'dumb-jump-mode)
(add-hook 'javascript-mode 'dumb-jump-mode)
(add-hook 'latex-mode 'dumb-jump-mode)
(add-hook 'rust-mode 'dumb-jump-mode)
(add-hook 'sql-mode 'dumb-jump-mode)
(add-hook 'haskell-mode 'dumb-jump-mode)
(add-hook 'emacs-lisp-mode 'dumb-jump-mode)
(add-hook 'python-mode 'dumb-jump-mode)
(add-hook 'php-mode 'dumb-jump-mode)

(global-set-key (kbd "C-c d g") 'dumb-jump-go-current-window)
(global-set-key (kbd "C-c d p") 'dumb-jump-back)
