(require 'nlinum-relative)
(nlinum-relative-setup-evil)
(add-hook 'prog-mode-hook 'nlinum-relative-mode)
(setq nlinum-relative-redisplay-delay 0.0)
(setq nlinum-relative-current-symbol "")
(setq nlinum-relative-offset 0)
