(global-set-key (kbd "C-x t c") 'treemacs-create-file)
(global-set-key (kbd "C-x t d") 'treemacs-create-dir)
(global-set-key (kbd "C-x t a") 'treemacs-add-project-to-workspace)
(global-set-key (kbd "C-x t r") 'treemacs-rename)
(global-set-key (kbd "C-c RET") 'treemacs-RET-action)
(global-set-key (kbd "C-x t t") 'treemacs)
